name: 'Cloudflare Pages Dingding Webhook'
description: 'Wait for Cloudflare Pages to build and send Slack notification'
author: 'arddluma'
inputs:
  accountEmail:
    description: 'Your Cloudflare account email'
    required: false
  apiKey:
    description: 'Your Cloudflare API key'
    required: false
  apiToken:
    description: 'Your Cloudflare API token (alternative to email+key)'
    required: false
  dingWebHookKey:
    description: 'DingTalk webhook access token'
    required: false
  accountId:
    description: 'Cloudflare account ID'
    required: true
  project:
    description: 'Pages project name'
    required: true
  githubToken:
    description: 'GitHub Token to use for deployments (GITHUB_TOKEN secret or your own token!) - OPTIONAL (Only used for GitHub Deployments)'
    required: false
  commitHash:
    description: 'The commit hash of the commit triggered the target deployment'
    required: true
  slackWebHook:
    description: 'Slack incoming webhook url'
    required: false
outputs:
  id:
    description: 'Deployment ID'
  environment:
    description: 'Environment for this deployment, either "production" or "preview"'
  url:
    description: 'URL of the deployment'
  alias:
    description: 'Alias URL of the branch (for example: fix-navbar.project.pages.dev)'
  success:
    description: 'If the build passed or failed'
runs:
  using: 'node16'
  main: 'dist/action.js'
branding:
  icon: 'cloud'
  color: 'orange'
